version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:16
    container_name: db-postgres
    volumes:
      - asf_postgres_data:/bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=asf
    networks:
      - asf-network

  asf-server:
    image: asf-server:v4.1
    build:
      context: .
    container_name: asf-server
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - asf-network

networks:
  asf-network:
    name: asf-network
    driver: bridge

volumes:
  asf_postgres_data:
